export const INIT_STORE: StoreType = {
  clientSetting: {
    defaultLanguage: 'en',
    backgroundImagePrimary: '/assets/backgroundImages/00000.png',
    backgroundImageSecondary: '/assets/backgroundImages/00100.png',
    backgroundAudio: '/assets/audios/backgrounds/00000.mp3',
    touchAudio: '/assets/audios/touch/00000.mp3',
    videoIntro: '/assets/videos/introduces/00000.mp4',
    warningAudio: '/assets/audios/touch/00100.mp3',
    hardwareInfo: {
      camera: {
        name: '',
        serial: '',
        isOk: false,
      },
      network: {
        ipV4: '',
        mac: '',
        monitorIP: '',
        isOk: false,
      },
      screen: {
        width: null,
        height: null,
      },
      disk: null,
    },
  },
  resources: {
    backgroundImages: [],
    stickers: {
      hot: [],
      birthday: [],
      flowers: [],
      heart: [],
      others: [],
    },
    videos: {
      loading: [],
      introduces: [],
    },
    icons: [],
    audios: {
      backgrounds: [],
      touch: [],
    },
    frames: {
      cutting: {
        typeA: {
          normal: [],
          season: [],
          special: [],
        },
        typeB: {
          normal: [],
          season: [],
          special: [],
        },
        typeC: {
          normal: [],
          season: [],
          special: [],
        },
      },
      regular: {
        typeA: {
          normal: [],
          season: [],
          special: [],
        },
        typeB: {
          normal: [],
          season: [],
          special: [],
        },
        typeC: {
          normal: [],
          season: [],
          special: [],
        },
        typeD: {
          normal: [],
          season: [],
          special: [],
        },
        typeE: {
          normal: [],
          season: [],
          special: [],
        },
        typeF: {
          normal: [],
          season: [],
          special: [],
        },
      },
      wide: {
        typeA: {
          normal: [],
          season: [],
          special: [],
        },
        typeB: {
          normal: [],
          season: [],
          special: [],
        },
      },
    },
  },
  isLoading: false,
  assetsFolderPath: '',
  userPhotosFolderPath: '',
  orderInfo: {
    _id: '',
    orderNumber: '',
    orderType: '',
    orderBase: '',
    isGrayScale: false,
    grayScaleBase64: '',
    paymentMethod: 'CASH',
    paymentStatus: 'PENDING',
    frameMode: 'wide',
    frameType: 'typeA',
    frameStyle: 'season',
    frameNumber: 0,
    quantityShootingPhotos: 4,
    quantitySelectedPhotos: 2,
    frameRelPath: '/assets/frames/wide/typeA/season/00000.png',
    ratio: 1.5,
    width: 1200,
    height: 1800,
    framePrice: 30000,
    selectedPhotos: [],
    stickers: [],
    imageSelectPhoto: '',
    imageSelectEffect: '',
    imageSelectSticker: '',
    imageFrameSticker: '',
    imageFrameStickerDraw: '',
    videoBase64: '',
    printCount: 1,
    colorBase64: '',
    colorBase64NoQR: '',
    originalBase64: '',
    orderStatus: '',
    originalPrice: 0,
    finalPrice: 0,
    couponCode: '',
    discountPrice: 0,
    isDeleted: false,
    isVideoUploaded: false,
    isImageUploaded: false,
    currentPrintCount: 0,
    timeCode: '',
    effect: {
      name: 'Original',
      className: '',
      style: '',
    },
    shootingMethod: 'countdown',
    shootingTime: 15,
    createdAt: '',
    updatedAt: '',
  },
};

export const INIT_THEME: ThemeType = {
  pink: 'pink',
};
